### ISSUE TITLE
Exception in Thread-1

### ISSUE THREAD

**Issue by ChrisFischer-MTA** [qubard/mcidle-python#2]
Good Evening,

I am attempting to use this program on a linux distro. I've ensured I have the dependencies at the required versions. In attempting to start the server, I am getting the following error:

    Credentials are valid!
    Started thread
    Started thread
    Started thread
    Started thread
    Started thread
    Started thread
    Started thread
    Started thread
    Started thread
    Started thread
    Started thread
    Started thread
    Started thread
    Started thread
    Started thread
    Started thread
    Connected
    Waiting for client
    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
        self.run()
      File "/home/ubuntu/mcidle-python-master/src/networking/connection.py", line 65, in run
        self.packet_handler.handle()
      File "/home/ubuntu/mcidle-python-master/src/networking/packet_handler/serverbound/login_handler.py", line 10, in handle
        self.login()
      File "/home/ubuntu/mcidle-python-master/src/networking/packet_handler/serverbound/login_handler.py", line 45, in login
        set_compression = SetCompression().read(self.read_packet().packet_buffer)
      File "/home/ubuntu/mcidle-python-master/src/networking/packets/packet.py", line 48, in     read
        assert (id_ == self.id or (self.ids and id_ in self.ids))
    AssertionError

I've attempted two different servers. I'm looking for guidance on where to go from here. (I've also switched port numbers and rebooted to ensure sessions aren't conflicting with each other.

**Comment by qubard** [comment]
What was the server version? It looks like the server did not send a set compression packet. This is prob a bug since I didn't test for it. I'll get a fix out ASAP.

**Comment by ChrisFischer-MTA** [comment]
It was a server that accepts connections from multiple clients, in the 1.8-1.14 range.

Also, if you give me a general idea of how you find the packet IDs (I have experience w/ doing pcaps and reading source) I can absolutely make some contributions for you via the repo.

**Comment by qubard** [comment]
Sorry for the delayed response, been busy irl

Protocol version numbers/packet ids for various game versions can be found here. https://wiki.vg/Protocol_version_numbers

The main problem w/ it not working with other versions than 1.12.2 is because I didn't actually write the mapper that maps version numbers to protocol numbers to each packet's structure and catches version inconsistencies. I should be able to get that done later this week unless someone submits a pull that does this already.

Also, 

The reason your game crashed is because I didn't allow for any flexibility with packets where compression on the server was not sent which was an oversight. I think it didn't send it because it didn't allow you to connect since for the LoginStart packet I send the player's username but it was default in run.py set to "leddit" and broke everything. The latest commit should work and I've just tested it on 1.12.2. Gonna work on the mapping for more versions, let me know if it doesn't work still.

**Comment by ChrisFischer-MTA** [comment]
Works. Sorry for the late reply. Thanks agin!
