### ISSUE TITLE
server not working

### ISSUE THREAD

**Issue by ghost** [qubard/mcidle-python#7]
After running mcidle there is a pretty long pause between the first "Done sending handshake" and "Set upstream socket", but that's not the real issue.
I'm getting this 
```
Exception Unexpected end of message.
Called MinecraftConnection::on_disconnect()...
Socket shutdown and closed.
Disconnected..reconnecting in 10 seconds
```

a few times before it's actually connecting to 2b2t as my user.
Then the chat messages are received and working in the console, but after some time the errors are coming again like before.
I obviously can't connect to the local server.

The command I used is:  
> screen -S mcidle -L -Logfile mcidle_log.log mcidle --username=MY@EMAIL --password=MYPASSWORD --ip=2b2t.org --dport=25565

I also tried using 0.0.0.0 or the local IP as server IP but I'm getting the same results every time.

**System:** Raspberry Pi 3

**Log:** https://pastebin.com/eMs89aR5

**Comment by qubard** [comment]
It seems like it's connecting but eventually breaking because the socket breaks. Someone else had a similar problem with running it on the Raspberry Pi. I've never had this issue on any desktop so it seems to be unique to the pi. It's really slow to read packets so most of the CPU is spent reading packets so when a keep alive comes in there is a huge backlog and eventually the client is disconnected by the server, and no output is logged. 

I would look into the CPU usage and see if it's reaching 100% at any point to confirm this

AS an aside, the [C++ version ](https://github.com/qubard/mcidle-cpp/). which isn't released yet already supports chunk serialization and is quite literally 50x faster than the Python version so I'd wait for that to come out. It would definitely run on the pi.

**Comment by ghost** [comment]
`1224 pi        20   0   63960  18672   8332 S 119.9   2.0   1:01.90 mcidle`
This is what htop is giving me on one of 7 mcidle commands... The other ones stay under 100% most of the time. Some cores hit 100% a few times.
I'll surely wait for the C++ version but I would've liked to get this running :/

**Comment by qubard** [comment]
Not intended to work on rpi. The C++ version *might* work on RPI, but a lot of the compiled libs like for openssl may break
